// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFYKZx7gQtAB3gnQTD7DzPwKpE00jc1sA',
    appId: '1:955098676713:web:fde3435c79d1672553df78',
    messagingSenderId: '955098676713',
    projectId: 'sporthub-d9a6b',
    authDomain: 'sporthub-d9a6b.firebaseapp.com',
    storageBucket: 'sporthub-d9a6b.firebasestorage.app',
    measurementId: 'G-VDXLH3QVD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ2HpE5567Kmk2kiPIUgEm8_S7YX9BUhE',
    appId: '1:955098676713:android:70f8d5387e0eceb653df78',
    messagingSenderId: '955098676713',
    projectId: 'sporthub-d9a6b',
    storageBucket: 'sporthub-d9a6b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy4Kmsq7Q5l5Zws1JeOFcufZy_15XZanA',
    appId: '1:955098676713:ios:8914789f137ccb6e53df78',
    messagingSenderId: '955098676713',
    projectId: 'sporthub-d9a6b',
    storageBucket: 'sporthub-d9a6b.firebasestorage.app',
    iosBundleId: 'com.sporthub.prm393.sporthub',
  );
}
